seed: 42
num_workers : 4

model_name   : 'sgaligner'
modules      : ['gat', 'point', 'rel', 'attr']
registration : True

data :
  name            : Scan3R
  root_dir        : /drive/datasets/Scan3R
  subscan_dir      : /drive/dumps/sgaligner/subscans/Scan3R
  label_file_name : labels.instances.align.annotated.v2.ply

preprocess :
  pc_resolutions      : [512]
  subscenes_per_scene : 7
  min_obj_points      : 50
  anchor_type_name    : '' 